import React from "react";
import { getPokemonAction, nextPokemonAction } from "../redux/pokeDucks";
// react-redux Hooks, useDispach() Executes 'Actions', useSelector() Reads final array/ results (main state) generated by dispatch() methods (Actions)
import { useDispatch, useSelector } from "react-redux";

export const Pokemones = () => {
  const dispatch = useDispatch(); // Initialize dispatch()
  // useSelector() access to store.js 'rootReducer' (contains all reducers (results) and get 'pokemones' reducer RESULT)
  const pokemones = useSelector((store) => store.pokemones.array);
    const ready = useSelector((store) => store.pokemones.ready);

   console.log(ready) // data in Array-format (20 items)

  return (
    <div className="container">
      <h1>Poke List using Redux to global variables and Axios to get Data</h1>
      {/* Execute Actions with dispatch()*/}
      { !ready ? (
        <button
          className="btn btn-warning p-3 m-2"
          onClick={() => dispatch(getPokemonAction())}
        >
          Get Poke
        </button>
      ) : null }
      <button
        className="btn btn-secondary p-3"
        onClick={() => dispatch(nextPokemonAction())}
      >
        Next Poke (20)
      </button>

      <ul>
        {/* Iterate data captured by useSelector() thorugh dispatch() method */}
        {pokemones.map((pokemon) => (
          <li key={pokemon.name}> {pokemon.name}</li>
        ))}
      </ul>
    </div>
  );
};

export default Pokemones;
